### ISSUE TITLE
Certain fields are not parsed correctly

### ISSUE THREAD

**Issue by huijing** [HiDeoo/starlight-openapi#12]
### Describe the bug

There are 2 striking issues that occur when I'm trying to parse our OpenAPI specification.

1. When `oneOf` is used, the plugin parses the array into tabs, but the tab item headers are unknown. Please refer to attached screenshot which shows the specification and rendered output using Swagger Editor, compared with the plugin output
    
    ![Screenshot 2023-10-18 at 11 56 41 PM](https://github.com/HiDeoo/starlight-openapi/assets/1461498/2791a322-d056-4498-bb3d-a8928b9e735c)

2. When the type is an array, nested information is not rendered. Please refer to attached screenshots as well.

    ![Screenshot 2023-10-19 at 11 51 50 AM](https://github.com/HiDeoo/starlight-openapi/assets/1461498/d60480ae-4915-4bbb-aa2b-8bd983b81ab5)

    ![Screenshot 2023-10-19 at 12 01 02 PM](https://github.com/HiDeoo/starlight-openapi/assets/1461498/2e0e6439-9a01-4c0f-b8a7-3d3ff26a1a23)

### To Reproduce

1. Load the YAML files attached at the end of the issue
2. Go to the page for `Grant Request`, which will show up nested under `grant` in the generated sidebar item
    3. At the request body section, for the `access_token` field, as well as the `interact` field, you can see the array issue
    4. Scroll further down to `Responses` and you can see the unknown tab title issue
5. Another page where this happens is the `Create a quote` page nested under `quote` in the generated sidebar item
    6. Under request body, you can see the unknown tab item issue as well
    7. On this page you can also see that authorizations ends up being rendered as a list item and nothing more, this might be more of a additional feature than a bug maybe?

### Expected behavior

1. I'm not sure if the tabs are necessary, but based on the behaviour on SwaggerEditor, I suppose just putting the array index as the tab title would be better than "unknown"?
2. For this, the expected behaviour would be that the nested information is parsed throughly, just like it is being done for items of type object.

### How often does this bug happen?

Every time

### System Info

- Operating System: macOS 13.5.2
- Browser: Chrome
- Version: 119.0.6018.4

But this issue is unrelated to the system.

### Additional Context

These are the specification files where the issues occur. You can upload them to https://editor-next.swagger.io/ for see the comparison versus loading them with the plugin.
- https://raw.githubusercontent.com/huijing/filerepo/gh-pages/auth.yaml
- https://raw.githubusercontent.com/huijing/filerepo/gh-pages/resource.yaml

**Comment by HiDeoo** [comment]
Thanks for the detailed report. These issues should be fixed in [`v0.3.1`](https://github.com/HiDeoo/starlight-openapi/releases/tag/v0.3.1) that I just published on npm.

Some arrays were missing object details, they should now render correctly.

<img width="1070" alt="SCR-20231019-kwyk" src="https://github.com/HiDeoo/starlight-openapi/assets/494699/3c39dc18-e709-43eb-960c-7c02f42553a7">

Still related to arrays, enums informations were not displayed correctly, this should now be fixed.

<img width="630" alt="SCR-20231019-lexs" src="https://github.com/HiDeoo/starlight-openapi/assets/494699/7fc6267b-fbf9-4ce1-94a1-0617db759131">

Regarding the "unknown" `oneOf`, 2 issues were involved: the labels of the tabs being "unknown" and the tabs content actually missing. Both should render correctly now.

<img width="1107" alt="SCR-20231019-kivy" src="https://github.com/HiDeoo/starlight-openapi/assets/494699/7a5600eb-8c3d-4614-956f-8783e6f77539">

<img width="1104" alt="SCR-20231019-kiyg" src="https://github.com/HiDeoo/starlight-openapi/assets/494699/f89cefdf-8ae2-496f-94fb-4312511676d1">

Regarding the authorizations, each authorization is now a link to the corresponding security scheme which contains all the informations.

<img width="261" alt="SCR-20231019-lzxg" src="https://github.com/HiDeoo/starlight-openapi/assets/494699/d451f23f-8f91-4639-9585-37f3211506c8">

<img width="1104" alt="SCR-20231019-lzug" src="https://github.com/HiDeoo/starlight-openapi/assets/494699/2626e710-6345-4888-a94b-717aaf4636bc">
