### ISSUE TITLE
Starlight components reading translations from Astro.props.labels property not working from starlight@0.14.0

### ISSUE THREAD

**Issue by alexXxSG** [HiDeoo/starlight-openapi#14]
### Describe the bug

Starlight 0.14.0 exposes a `labels` property in Starlight’s route data object for each page -> https://github.com/withastro/starlight/pull/1135 , so all components can read that property instead of using t(). `starlight-openapi` is not including that property when creating the StarlightPage, so an exception is raised, i.e:  `TypeError: Cannot read properties of undefined (reading 'themeSelect.accessibleLabel')`

### To Reproduce

1. Install the following dependecies
  - "@astrojs/starlight": "0.15.0"
  - "astro": "4.0.3"
2. Start the project and browse to an operation page

### Expected behavior

As i18n is not yet supported, it should generate the operation pages without translating, just using the default lang

### How often does this bug happen?

Every time

**Comment by HiDeoo** [comment]
Thanks for the report.

Indeed, any usage of the built-in `<Page/>` component are a bit broken since Starlight `v0.14.0`. I submitted a [PR](https://github.com/withastro/starlight/pull/1175) with a lot of details and an attempt to fix the issue.

> As i18n is not yet supported, it should generate the operation pages without translating, just using the default lang

This is unfortunately not something we can do as even the default language UI strings for all Starlight internal components are expected to be passed down as props.

**Comment by alexXxSG** [comment]
Thanks for the info, I will keep an eye on it!

**Comment by HiDeoo** [comment]
Thanks for your patience with this issue. 

[`v0.5.0`](https://github.com/HiDeoo/starlight-openapi/releases/tag/v0.5.0) fixes the issue, e.g. this [demo page](https://starlight-openapi.vercel.app/api/petstore/operations/addpet) which uses the latest Starlight version.
