### ISSUE TITLE
Styling incorrect for object requests

### ISSUE THREAD

**Issue by azan-n** [HiDeoo/starlight-openapi#21]
### Describe the bug

<img width="706" alt="image" src="https://github.com/HiDeoo/starlight-openapi/assets/31279909/7c8e45a5-2427-43e1-9748-f54ec89b57e2">
This is a query parameter. The description is at the bottom after all the properties are defined.

### To Reproduce

Parameter defined as

```json
{
    "name": "productId",
    "in": "query",
    "description": "Unique identifier for the product.",
    "schema": {
      "type": "object",
      "properties": {
        "eq": {
          "type": "string",
          "description": "Matches values that are equal to the specified value.",
          "format": "string"
        },
        "ne": {
          "type": "string",
          "description": "Matches values that are not equal to the specified value.",
          "format": "string"
        },
        "in": {
          "type": "string",
          "description": "Matches any of the values specified.",
          "format": "comma-separated-values"
        },
        "nin": {
          "type": "string",
          "description": "Matches none of the values specified.",
          "format": "comma-separated-values"
        }
      }
    }
},
```

### Expected behavior

The parameter description should come first and the properties and their descriptions should come later. We can also add some sense of hierarchy using indentation.

### How often does this bug happen?

Every time

**Comment by HiDeoo** [comment]
The issue should now be fixed in [`v0.6.0`](https://github.com/HiDeoo/starlight-openapi/releases/tag/v0.6.0) that I just published.

**Before:**

<img width="394" alt="SCR-20240323-kmvu" src="https://github.com/HiDeoo/starlight-openapi/assets/494699/29ee4126-c6c5-420d-9d5c-7c34054951c6">

**After:**

<img width="394" alt="SCR-20240323-kmyj" src="https://github.com/HiDeoo/starlight-openapi/assets/494699/7eeb5002-d3fa-48fa-9165-0ed5f36016db">
